print('---DESAFIO 04---')

dado =  input('Digite algo.')
print('O tipo primitivo do dado é: ',type(dado))
print('É somente espaços? ', dado.isspace())
print('É alfanumérico? ', dado.isalnum())
print('É alfabético? ', dado.isalpha())
print('É ASCII?', dado.isascii())
print('É decimal? ', dado.isdecimal())
print('É digito? ', dado.isdigit())
print('É identificador? ', dado.isidentifier())
print('Está em minúsculo? ', dado.islower())
print('É numérico? ', dado.isnumeric())
print('É possivel imprimir? ', dado.isprintable())
print('É um título? ', dado.istitle())
print('Está em maiúsculo? ', dado.isupper())
